const SEED_MOSQUES = [
  {
    id: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6",
    osm_id: 100001,
    name: "Hazrati Imom (Hastimom) Masjidi",
    alt_name: "Hazrat Imam Mosque",
    address: "Qorasaroy ko'chasi, Olmazor tumani, Toshkent, O'zbekiston",
    city: "Toshkent",
    country: "O'zbekiston",
    type: "masjid",
    lat: 41.3381,
    lng: 69.2415,
    has_wudu_men: true,
    has_wudu_women: true,
    has_women_prayer_area: true,
    has_juma: true,
    has_wheelchair_access: true,
    has_parking: true,
    photo_url: "https://images.unsplash.com/photo-1590076212455-83e9ea43a18e?w=800",
    status: "approved",
    verified_count: 48
  },
  {
    id: "f81d4fae-7dec-11d0-a765-00a0c91e6bf7",
    osm_id: 100002,
    name: "Minor Masjidi",
    alt_name: "Minor Mosque",
    address: "Kichik halqa yo'li, Yunusobod tumani, Toshkent, O'zbekiston",
    city: "Toshkent",
    country: "O'zbekiston",
    type: "masjid",
    lat: 41.3283,
    lng: 69.2817,
    has_wudu_men: true,
    has_wudu_women: true,
    has_women_prayer_area: true,
    has_juma: true,
    has_wheelchair_access: true,
    has_parking: true,
    photo_url: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800",
    status: "approved",
    verified_count: 52
  },
  {
    id: "f81d4fae-7dec-11d0-a765-00a0c91e6bf8",
    osm_id: 100003,
    name: "Shayx Zayniddin (Ko'kcha) Masjidi",
    alt_name: "Kukcha Mosque",
    address: "Ko'kcha Darvoza ko'chasi, Shayxontohur tumani, Toshkent, O'zbekiston",
    city: "Toshkent",
    country: "O'zbekiston",
    type: "masjid",
    lat: 41.3214,
    lng: 69.2141,
    has_wudu_men: true,
    has_wudu_women: true,
    has_women_prayer_area: true,
    has_juma: true,
    has_wheelchair_access: true,
    has_parking: true,
    photo_url: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=800",
    status: "approved",
    verified_count: 40
  },
  {
    id: "f81d4fae-7dec-11d0-a765-00a0c91e6bf9",
    osm_id: 100004,
    name: "Tashkent City Mall Musalla",
    alt_name: "Shopping Center Prayer Room",
    address: "Botir Zokirov ko'chasi, Tashkent City, Toshkent",
    city: "Toshkent",
    country: "O'zbekiston",
    type: "musalla",
    lat: 41.3115,
    lng: 69.2530,
    has_wudu_men: true,
    has_wudu_women: true,
    has_women_prayer_area: true,
    has_juma: false,
    has_wheelchair_access: true,
    has_parking: true,
    photo_url: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800",
    status: "approved",
    verified_count: 22
  },
  {
    id: "f81d4fae-7dec-11d0-a765-00a0c91e6bfa",
    osm_id: 100005,
    name: "Aeroport Musallasi (Terminal 2)",
    alt_name: "Tashkent International Airport Prayer Room",
    address: "Islom Karimov nomidagi Toshkent xalqaro aeroporti, Toshkent",
    city: "Toshkent",
    country: "O'zbekiston",
    type: "musalla",
    lat: 41.2575,
    lng: 69.2811,
    has_wudu_men: true,
    has_wudu_women: true,
    has_women_prayer_area: true,
    has_juma: false,
    has_wheelchair_access: true,
    has_parking: true,
    photo_url: "https://images.unsplash.com/photo-1519817650390-64a93db51149?w=800",
    status: "approved",
    verified_count: 35
  },
  {
    id: "f81d4fae-7dec-11d0-a765-00a0c91e6bfb",
    osm_id: 100006,
    name: "Al-Masjid an-Nabawi",
    alt_name: "Prophet's Mosque",
    address: "Al Haram, Medina 42311, Saudi Arabia",
    city: "Medina",
    country: "Saudi Arabia",
    type: "masjid",
    lat: 24.4672,
    lng: 39.6111,
    has_wudu_men: true,
    has_wudu_women: true,
    has_women_prayer_area: true,
    has_juma: true,
    has_wheelchair_access: true,
    has_parking: true,
    photo_url: "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=800",
    status: "approved",
    verified_count: 500
  },
  {
    id: "f81d4fae-7dec-11d0-a765-00a0c91e6bfc",
    osm_id: 100007,
    name: "Al-Masjid al-Haram",
    alt_name: "The Sacred Mosque",
    address: "Al Haram, Mecca 24231, Saudi Arabia",
    city: "Mecca",
    country: "Saudi Arabia",
    type: "masjid",
    lat: 21.4225,
    lng: 39.8262,
    has_wudu_men: true,
    has_wudu_women: true,
    has_women_prayer_area: true,
    has_juma: true,
    has_wheelchair_access: true,
    has_parking: true,
    photo_url: "https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?w=800",
    status: "approved",
    verified_count: 1000
  },
  {
    id: "f81d4fae-7dec-11d0-a765-00a0c91e6bfd",
    osm_id: 100008,
    name: "Sultanahmet Camii (Moviy Masjid)",
    alt_name: "Blue Mosque",
    address: "Sultan Ahmet, Atmeydanı Cd. No:7, Fatih/İstanbul, Türkiye",
    city: "Istanbul",
    country: "Turkiya",
    type: "masjid",
    lat: 41.0054,
    lng: 28.9768,
    has_wudu_men: true,
    has_wudu_women: true,
    has_women_prayer_area: true,
    has_juma: true,
    has_wheelchair_access: true,
    has_parking: false,
    photo_url: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=800",
    status: "approved",
    verified_count: 310
  },
  {
    id: "f81d4fae-7dec-11d0-a765-00a0c91e6bfe",
    osm_id: 100009,
    name: "East London Mosque",
    alt_name: "East London Mosque & London Muslim Centre",
    address: "82-92 Whitechapel Rd, London E1 1JQ, United Kingdom",
    city: "London",
    country: "Buyuk Britaniya",
    type: "masjid",
    lat: 51.5185,
    lng: -0.0655,
    has_wudu_men: true,
    has_wudu_women: true,
    has_women_prayer_area: true,
    has_juma: true,
    has_wheelchair_access: true,
    has_parking: true,
    photo_url: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=800",
    status: "approved",
    verified_count: 140
  }
];

module.exports = { SEED_MOSQUES };
